// Sample recipe data organized by cuisine
export const recipes = [
    // French Recipes
    {
      id: "1",
      name: "Coq au Vin",
      cuisine: "French",
      prepTime: "30 min",
      cookTime: "1 hour",
      servings: 4,
      ingredients: [
        { id: "1", name: "Chicken thighs", amount: 8, unit: "pieces" },
        { id: "2", name: "Red wine", amount: 2, unit: "cups" },
        { id: "3", name: "Bacon", amount: 200, unit: "g" },
        { id: "4", name: "Mushrooms", amount: 250, unit: "g" },
        { id: "5", name: "Onions", amount: 2, unit: "pieces" },
        { id: "6", name: "Garlic", amount: 4, unit: "cloves" },
      ],
      instructions: [
        "Brown the chicken pieces in a large pot",
        "Add bacon and cook until crispy",
        "Add vegetables and cook until soft",
        "Pour in wine and simmer for 1 hour",
        "Serve with crusty bread",
      ],
    },
    {
      id: "2",
      name: "Ratatouille",
      cuisine: "French",
      prepTime: "20 min",
      cookTime: "45 min",
      servings: 6,
      ingredients: [
        { id: "1", name: "Eggplant", amount: 1, unit: "piece" },
        { id: "2", name: "Zucchini", amount: 2, unit: "pieces" },
        { id: "3", name: "Bell peppers", amount: 2, unit: "pieces" },
        { id: "4", name: "Tomatoes", amount: 4, unit: "pieces" },
        { id: "5", name: "Onion", amount: 1, unit: "piece" },
        { id: "6", name: "Olive oil", amount: 3, unit: "tbsp" },
      ],
      instructions: [
        "Slice all vegetables thinly",
        "Sauté onions in olive oil",
        "Layer vegetables in a baking dish",
        "Bake at 375°F for 45 minutes",
        "Serve hot or at room temperature",
      ],
    },
    {
      id: "3",
      name: "Crème Brûlée",
      cuisine: "French",
      prepTime: "15 min",
      cookTime: "40 min",
      servings: 4,
      ingredients: [
        { id: "1", name: "Heavy cream", amount: 2, unit: "cups" },
        { id: "2", name: "Egg yolks", amount: 6, unit: "pieces" },
        { id: "3", name: "Sugar", amount: 0.5, unit: "cup" },
        { id: "4", name: "Vanilla extract", amount: 1, unit: "tsp" },
      ],
      instructions: [
        "Heat cream until just simmering",
        "Whisk egg yolks with sugar",
        "Combine cream and egg mixture",
        "Bake in water bath at 325°F for 40 min",
        "Chill, then caramelize sugar on top",
      ],
    },
  
    // Danish Recipes
    {
      id: "4",
      name: "Smørrebrød",
      cuisine: "Danish",
      prepTime: "15 min",
      cookTime: "0 min",
      servings: 4,
      ingredients: [
        { id: "1", name: "Rye bread", amount: 8, unit: "slices" },
        { id: "2", name: "Butter", amount: 100, unit: "g" },
        { id: "3", name: "Pickled herring", amount: 200, unit: "g" },
        { id: "4", name: "Hard-boiled eggs", amount: 4, unit: "pieces" },
        { id: "5", name: "Red onion", amount: 1, unit: "piece" },
        { id: "6", name: "Dill", amount: 1, unit: "bunch" },
      ],
      instructions: [
        "Butter each slice of rye bread generously",
        "Top with pickled herring",
        "Add sliced hard-boiled eggs",
        "Garnish with red onion and fresh dill",
        "Serve immediately",
      ],
    },
    {
      id: "5",
      name: "Frikadeller",
      cuisine: "Danish",
      prepTime: "20 min",
      cookTime: "20 min",
      servings: 6,
      ingredients: [
        { id: "1", name: "Ground pork", amount: 500, unit: "g" },
        { id: "2", name: "Ground veal", amount: 250, unit: "g" },
        { id: "3", name: "Onion", amount: 1, unit: "piece" },
        { id: "4", name: "Egg", amount: 1, unit: "piece" },
        { id: "5", name: "Flour", amount: 3, unit: "tbsp" },
        { id: "6", name: "Milk", amount: 0.5, unit: "cup" },
      ],
      instructions: [
        "Mix all ingredients in a large bowl",
        "Form into oval patties",
        "Fry in butter until golden brown",
        "Serve with potatoes and pickled beets",
        "Enjoy with gravy",
      ],
    },
    {
      id: "6",
      name: "Æbleskiver",
      cuisine: "Danish",
      prepTime: "10 min",
      cookTime: "15 min",
      servings: 20,
      ingredients: [
        { id: "1", name: "Flour", amount: 2, unit: "cups" },
        { id: "2", name: "Buttermilk", amount: 2, unit: "cups" },
        { id: "3", name: "Eggs", amount: 2, unit: "pieces" },
        { id: "4", name: "Sugar", amount: 2, unit: "tbsp" },
        { id: "5", name: "Baking powder", amount: 1, unit: "tsp" },
        { id: "6", name: "Butter", amount: 100, unit: "g" },
      ],
      instructions: [
        "Mix dry ingredients together",
        "Add buttermilk and beaten eggs",
        "Heat æbleskiver pan with butter",
        "Fill each well 3/4 full",
        "Turn with a skewer until golden all over",
      ],
    },
  
    // Italian Recipes
    {
      id: "7",
      name: "Pasta Carbonara",
      cuisine: "Italian",
      prepTime: "10 min",
      cookTime: "15 min",
      servings: 4,
      ingredients: [
        { id: "1", name: "Spaghetti", amount: 400, unit: "g" },
        { id: "2", name: "Guanciale", amount: 200, unit: "g" },
        { id: "3", name: "Egg yolks", amount: 4, unit: "pieces" },
        { id: "4", name: "Pecorino Romano", amount: 100, unit: "g" },
        { id: "5", name: "Black pepper", amount: 1, unit: "tsp" },
      ],
      instructions: [
        "Cook pasta in salted boiling water",
        "Crisp guanciale in a pan",
        "Mix egg yolks with grated cheese",
        "Toss hot pasta with guanciale",
        "Add egg mixture off heat, stirring quickly",
      ],
    },
    {
      id: "8",
      name: "Risotto alla Milanese",
      cuisine: "Italian",
      prepTime: "10 min",
      cookTime: "25 min",
      servings: 4,
      ingredients: [
        { id: "1", name: "Arborio rice", amount: 300, unit: "g" },
        { id: "2", name: "Chicken stock", amount: 1, unit: "l" },
        { id: "3", name: "White wine", amount: 0.5, unit: "cup" },
        { id: "4", name: "Saffron", amount: 0.5, unit: "tsp" },
        { id: "5", name: "Butter", amount: 50, unit: "g" },
        { id: "6", name: "Parmesan", amount: 100, unit: "g" },
      ],
      instructions: [
        "Toast rice in butter",
        "Add wine and let it absorb",
        "Add stock one ladle at a time, stirring",
        "Add saffron halfway through",
        "Finish with butter and parmesan",
      ],
    },
  
    // American Recipes
    {
      id: "9",
      name: "BBQ Pulled Pork",
      cuisine: "American",
      prepTime: "15 min",
      cookTime: "8 hours",
      servings: 8,
      ingredients: [
        { id: "1", name: "Pork shoulder", amount: 2, unit: "kg" },
        { id: "2", name: "BBQ sauce", amount: 2, unit: "cups" },
        { id: "3", name: "Brown sugar", amount: 0.25, unit: "cup" },
        { id: "4", name: "Paprika", amount: 2, unit: "tbsp" },
        { id: "5", name: "Garlic powder", amount: 1, unit: "tbsp" },
      ],
      instructions: [
        "Rub pork with spices",
        "Cook in slow cooker on low for 8 hours",
        "Shred meat with two forks",
        "Mix with BBQ sauce",
        "Serve on buns with coleslaw",
      ],
    },
    {
      id: "10",
      name: "Apple Pie",
      cuisine: "American",
      prepTime: "30 min",
      cookTime: "50 min",
      servings: 8,
      ingredients: [
        { id: "1", name: "Pie crust", amount: 2, unit: "pieces" },
        { id: "2", name: "Apples", amount: 6, unit: "pieces" },
        { id: "3", name: "Sugar", amount: 0.75, unit: "cup" },
        { id: "4", name: "Cinnamon", amount: 1, unit: "tsp" },
        { id: "5", name: "Butter", amount: 2, unit: "tbsp" },
      ],
      instructions: [
        "Peel and slice apples",
        "Mix apples with sugar and cinnamon",
        "Place bottom crust in pie dish",
        "Add apple mixture and dot with butter",
        "Top with second crust and bake at 375°F for 50 min",
      ],
    },
  ];
  
  // Organize recipes by cuisine for SectionList
  export const getRecipesByCuisine = () => {
    const cuisines = [...new Set(recipes.map((r) => r.cuisine))];
    return cuisines.map((cuisine) => ({
      title: cuisine,
      data: recipes.filter((r) => r.cuisine === cuisine),
    }));
  };