// Sample recipe data organized by cuisine
export const recipes = [
    // French Recipes
    {
      id: "1",
      name: "Coq au Vin",
      cuisine: "French",
      category: "Dinner",
      prepTime: "30 min",
      cookTime: "1 hour",
      servings: 4,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/coq-au-vin.jpg",
      ingredients: [
        { id: "1", name: "Chicken thighs", amount: 8, unit: "pieces" },
        { id: "2", name: "Red wine", amount: 2, unit: "cups" },
        { id: "3", name: "Bacon", amount: 200, unit: "g" },
        { id: "4", name: "Mushrooms", amount: 250, unit: "g" },
        { id: "5", name: "Onions", amount: 2, unit: "pieces" },
        { id: "6", name: "Garlic", amount: 4, unit: "cloves" },
      ],
      instructions: [
        "Brown the chicken pieces in a large pot",
        "Add bacon and cook until crispy",
        "Add vegetables and cook until soft",
        "Pour in wine and simmer for 1 hour",
        "Serve with crusty bread",
      ],
    },
    {
      id: "2",
      name: "Ratatouille",
      cuisine: "French",
      category: "Entrée",
      prepTime: "20 min",
      cookTime: "45 min",
      servings: 6,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/ratatouille.jpg",
      ingredients: [
        { id: "1", name: "Eggplant", amount: 1, unit: "piece" },
        { id: "2", name: "Zucchini", amount: 2, unit: "pieces" },
        { id: "3", name: "Bell peppers", amount: 2, unit: "pieces" },
        { id: "4", name: "Tomatoes", amount: 4, unit: "pieces" },
        { id: "5", name: "Onion", amount: 1, unit: "piece" },
        { id: "6", name: "Olive oil", amount: 3, unit: "tbsp" },
      ],
      instructions: [
        "Slice all vegetables thinly",
        "Sauté onions in olive oil",
        "Layer vegetables in a baking dish",
        "Bake at 375°F for 45 minutes",
        "Serve hot or at room temperature",
      ],
    },
    {
      id: "3",
      name: "Crème Brûlée",
      cuisine: "French",
      category: "Dessert",
      prepTime: "15 min",
      cookTime: "40 min",
      servings: 4,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/creme-brulee.jpg",
      ingredients: [
        { id: "1", name: "Heavy cream", amount: 2, unit: "cups" },
        { id: "2", name: "Egg yolks", amount: 6, unit: "pieces" },
        { id: "3", name: "Sugar", amount: 0.5, unit: "cup" },
        { id: "4", name: "Vanilla extract", amount: 1, unit: "tsp" },
      ],
      instructions: [
        "Heat cream until just simmering",
        "Whisk egg yolks with sugar",
        "Combine cream and egg mixture",
        "Bake in water bath at 325°F for 40 min",
        "Chill, then caramelize sugar on top",
      ],
    },
    {
      id: "11",
      name: "Boeuf Bourguignon",
      cuisine: "French",
      category: "Dinner",
      prepTime: "30 min",
      cookTime: "2.5 hours",
      servings: 6,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/boeuf-bourg.jpg",
      ingredients: [
        { id: "1", name: "Beef chuck", amount: 1.5, unit: "kg" },
        { id: "2", name: "Red wine", amount: 3, unit: "cups" },
        { id: "3", name: "Bacon", amount: 200, unit: "g" },
        { id: "4", name: "Pearl onions", amount: 12, unit: "pieces" },
        { id: "5", name: "Carrots", amount: 3, unit: "pieces" },
        { id: "6", name: "Mushrooms", amount: 300, unit: "g" },
        { id: "7", name: "Tomato paste", amount: 2, unit: "tbsp" },
        { id: "8", name: "Beef stock", amount: 2, unit: "cups" },
      ],
      instructions: [
        "Cut beef into large chunks and brown in batches",
        "Cook bacon until crispy, set aside",
        "Sauté onions and carrots until caramelized",
        "Add tomato paste and cook for 1 minute",
        "Return beef to pot, add wine and stock",
        "Simmer covered for 2.5 hours until tender",
        "Add mushrooms in the last 30 minutes",
      ],
    },
    {
      id: "12",
      name: "Canard Confit",
      cuisine: "French",
      category: "Dinner",
      prepTime: "20 min",
      cookTime: "3 hours",
      servings: 4,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/duck-confit.jpg",
      ingredients: [
        { id: "1", name: "Duck legs", amount: 4, unit: "pieces" },
        { id: "2", name: "Duck fat", amount: 4, unit: "cups" },
        { id: "3", name: "Coarse salt", amount: 2, unit: "tbsp" },
        { id: "4", name: "Thyme", amount: 4, unit: "sprigs" },
        { id: "5", name: "Garlic", amount: 6, unit: "cloves" },
        { id: "6", name: "Bay leaves", amount: 2, unit: "pieces" },
      ],
      instructions: [
        "Season duck legs generously with salt",
        "Refrigerate overnight",
        "Rinse off salt and pat dry",
        "Place duck in deep pan with garlic, thyme, and bay leaves",
        "Cover completely with duck fat",
        "Cook in oven at 225°F for 3 hours",
        "Store in fat or crisp skin before serving",
      ],
    },
    {
      id: "13",
      name: "Poulet à la Crème de Champignons",
      cuisine: "French",
      category: "Dinner",
      prepTime: "15 min",
      cookTime: "45 min",
      servings: 4,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/poulet-champs.jpg",
      ingredients: [
        { id: "1", name: "Chicken breasts", amount: 4, unit: "pieces" },
        { id: "2", name: "Mushrooms", amount: 400, unit: "g" },
        { id: "3", name: "Heavy cream", amount: 1.5, unit: "cups" },
        { id: "4", name: "White wine", amount: 0.5, unit: "cup" },
        { id: "5", name: "Butter", amount: 3, unit: "tbsp" },
        { id: "6", name: "Shallots", amount: 2, unit: "pieces" },
        { id: "7", name: "Garlic", amount: 3, unit: "cloves" },
      ],
      instructions: [
        "Season chicken and brown in butter",
        "Remove chicken and set aside",
        "Sauté shallots and garlic until soft",
        "Add mushrooms and cook until golden",
        "Deglaze with white wine",
        "Add cream and return chicken to pan",
        "Simmer for 20 minutes until chicken is cooked through",
      ],
    },
  
    // Danish Recipes
    {
      id: "4",
      name: "Smørrebrød",
      cuisine: "Danish",
      category: "Entrée",
      prepTime: "15 min",
      cookTime: "0 min",
      servings: 4,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/smorrebrod.jpg",
      ingredients: [
        { id: "1", name: "Rye bread", amount: 8, unit: "slices" },
        { id: "2", name: "Butter", amount: 100, unit: "g" },
        { id: "3", name: "Pickled herring", amount: 200, unit: "g" },
        { id: "4", name: "Hard-boiled eggs", amount: 4, unit: "pieces" },
        { id: "5", name: "Red onion", amount: 1, unit: "piece" },
        { id: "6", name: "Dill", amount: 1, unit: "bunch" },
      ],
      instructions: [
        "Butter each slice of rye bread generously",
        "Top with pickled herring",
        "Add sliced hard-boiled eggs",
        "Garnish with red onion and fresh dill",
        "Serve immediately",
      ],
    },
    {
      id: "5",
      name: "Frikadeller",
      cuisine: "Danish",
      category: "Dinner",
      prepTime: "20 min",
      cookTime: "20 min",
      servings: 6,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/frika.jpg",
      ingredients: [
        { id: "1", name: "Ground pork", amount: 500, unit: "g" },
        { id: "2", name: "Ground veal", amount: 250, unit: "g" },
        { id: "3", name: "Onion", amount: 1, unit: "piece" },
        { id: "4", name: "Egg", amount: 1, unit: "piece" },
        { id: "5", name: "Flour", amount: 3, unit: "tbsp" },
        { id: "6", name: "Milk", amount: 0.5, unit: "cup" },
      ],
      instructions: [
        "Mix all ingredients in a large bowl",
        "Form into oval patties",
        "Fry in butter until golden brown",
        "Serve with potatoes and pickled beets",
        "Enjoy with gravy",
      ],
    },
    {
      id: "6",
      name: "Æbleskiver",
      cuisine: "Danish",
      category: "Dessert",
      prepTime: "10 min",
      cookTime: "15 min",
      servings: 20,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/aebleskiver.jpg",
      ingredients: [
        { id: "1", name: "Flour", amount: 2, unit: "cups" },
        { id: "2", name: "Buttermilk", amount: 2, unit: "cups" },
        { id: "3", name: "Eggs", amount: 2, unit: "pieces" },
        { id: "4", name: "Sugar", amount: 2, unit: "tbsp" },
        { id: "5", name: "Baking powder", amount: 1, unit: "tsp" },
        { id: "6", name: "Butter", amount: 100, unit: "g" },
      ],
      instructions: [
        "Mix dry ingredients together",
        "Add buttermilk and beaten eggs",
        "Heat æbleskiver pan with butter",
        "Fill each well 3/4 full",
        "Turn with a skewer until golden all over",
      ],
    },
    {
      id: "14",
      name: "Stegt Flæsk",
      cuisine: "Danish",
      category: "Dinner",
      prepTime: "10 min",
      cookTime: "20 min",
      servings: 4,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/stegt-flasek.jpg",
      ingredients: [
        { id: "1", name: "Pork belly", amount: 800, unit: "g" },
        { id: "2", name: "Potatoes", amount: 1, unit: "kg" },
        { id: "3", name: "Parsley", amount: 1, unit: "bunch" },
        { id: "4", name: "Butter", amount: 50, unit: "g" },
        { id: "5", name: "Salt", amount: 1, unit: "tsp" },
        { id: "6", name: "Pepper", amount: 0.5, unit: "tsp" },
      ],
      instructions: [
        "Score the pork skin in a crosshatch pattern",
        "Boil potatoes until tender",
        "Fry pork belly skin-side down until crispy",
        "Flip and cook until golden brown",
        "Make parsley sauce with butter and chopped parsley",
        "Serve pork with potatoes and parsley sauce",
      ],
    },
    {
      id: "15",
      name: "Flødeboller",
      cuisine: "Danish",
      category: "Dessert",
      prepTime: "30 min",
      cookTime: "0 min",
      servings: 12,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/floderboler.jpg",
      ingredients: [
        { id: "1", name: "Marzipan", amount: 200, unit: "g" },
        { id: "2", name: "Egg whites", amount: 3, unit: "pieces" },
        { id: "3", name: "Sugar", amount: 1, unit: "cup" },
        { id: "4", name: "Dark chocolate", amount: 300, unit: "g" },
        { id: "5", name: "Vanilla extract", amount: 1, unit: "tsp" },
      ],
      instructions: [
        "Roll marzipan into small discs for bases",
        "Beat egg whites until stiff peaks form",
        "Gradually add sugar while beating",
        "Pipe meringue onto marzipan bases",
        "Let set for 30 minutes",
        "Melt chocolate and coat each flødebolle",
        "Let chocolate set before serving",
      ],
    },
    {
      id: "16",
      name: "Leverpostej",
      cuisine: "Danish",
      category: "Entrée",
      prepTime: "20 min",
      cookTime: "1 hour",
      servings: 8,
      imageUrl: "/Users/killiand/Desktop/Ecole/ACSQ7/ACS3340/final-project/images/leverpostej.jpg",
      ingredients: [
        { id: "1", name: "Pork liver", amount: 500, unit: "g" },
        { id: "2", name: "Pork fat", amount: 300, unit: "g" },
        { id: "3", name: "Onions", amount: 2, unit: "pieces" },
        { id: "4", name: "Anchovies", amount: 4, unit: "pieces" },
        { id: "5", name: "Flour", amount: 3, unit: "tbsp" },
        { id: "6", name: "Eggs", amount: 2, unit: "pieces" },
        { id: "7", name: "Milk", amount: 1, unit: "cup" },
      ],
      instructions: [
        "Grind liver, fat, onions, and anchovies",
        "Mix in flour, eggs, and milk",
        "Season with salt, pepper, and allspice",
        "Pour into a greased loaf pan",
        "Cover with foil and bake at 350°F for 1 hour",
        "Cool and serve on rye bread with pickles",
      ],
    },
  ];
  
  // Organize recipes by cuisine for SectionList
  export const getRecipesByCuisine = () => {
    const cuisines = [...new Set(recipes.map((r) => r.cuisine))];
    return cuisines.map((cuisine) => ({
      title: cuisine,
      data: recipes.filter((r) => r.cuisine === cuisine),
    }));
  };
  
  // Get unique categories for filtering
  export const getCategories = () => {
    return [...new Set(recipes.map((r) => r.category))];
  };